<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookApp.Enitites\BookApp.Entities.csproj" />
      <ProjectReference Include="..\BookApp.Persistence\BookApp.Persistence.csproj" />
      <ProjectReference Include="..\BookApp.Services.Api\BookApp.Services.Api.csproj" />
    </ItemGroup>

</Project>
